db:
  image: mariadb:10.3
  restart: always
  volumes:
    - /var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: db
    MYSQL_USER: admin
    MYSQL_PASSWORD: pass
web:
  hostname: 'bratstvo-film.ru'
  image: dimaip/docker-neos-alpine:latest
  ports:
    - '80'
    - '1126:22'
  links:
    - db:db
  volumes:
    - /data
    - ./Persistent:/data/shared/Data/Persistent
  environment:
    - PHP_TIMEZONE=Europe/Moscow
    - VIRTUAL_HOST=bratstvo-film.ru,www.bratstvo-film.ru,dev.bratstvo-film.ru,next.bratstvo-film.ru
    - REPOSITORY_URL=https://github.com/psmb/BratstvoMovieDistr
    - LETSENCRYPT_HOST=bratstvo-film.ru,www.bratstvo-film.ru
    - LETSENCRYPT_EMAIL=dimaip@gmail.com
    - IMPORT_GITHUB_PUB_KEYS=dimaip
    - AWS_ENDPOINT=https://hb.bizmrg.com
    - AWS_BACKUP_ARN=s3://psmb-neos-resources/db/bratstvofilm/
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
