
TYPO3:
  Neos:
    typoScript:
      autoInclude:
        Sfi.Site: true
    userInterface:
      navigateComponent:
        nodeTree:
          loadingDepth: 1
  TYPO3CR:
    contentDimensions:
      language:
        default: ru
        defaultPreset: ru
        label: Language
        icon: icon-language
        presets:
          ru:
            label: Russian
            values:
              - ru
            uriSegment: ''
          en:
            label: English
            values:
              - en
            uriSegment: en
Flownative:
  Aws:
    S3:
      profiles:
        default:
          credentials:
            key: '%env:AWS_ACCESS_KEY_ID%'
            secret: '%env:AWS_SECRET_ACCESS_KEY%'
          endpoint: 'https://hb.bizmrg.com'
Neos:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: db
        user: admin
        password: pass
        host: db
        port: 3306
    i18n:
      defaultLocale: ru
    resource:
      collections:
        persistent:
          storage: s3PersistentResourcesStorage
          target: s3PersistentResourcesTarget
      storages:
        s3PersistentResourcesStorage:
          storage: Flownative\Aws\S3\S3Storage
          storageOptions:
            bucket: psmb-neos-resources
            keyPrefix: storage/bratstvofilm/
      targets:
        s3PersistentResourcesTarget:
          target: Flownative\Aws\S3\S3Target
          targetOptions:
            bucket: psmb-neos-resources
            keyPrefix: target/bratstvofilm/
            baseUri: 'https://psmb-neos-resources.hb.bizmrg.com/target/bratstvofilm/'
